# fly.toml app configuration file generated for bookmarksfac28 on 2023-10-03T12:05:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookmarksfac28"
primary_region = "lhr"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
